# Generated by Django 3.1.6 on 2021-02-21 23:37

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photograph',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=reports.models.reportCaptures),
        ),
    ]
