# Generated by Django 3.1.6 on 2021-03-28 21:46

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='audio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=notifications.models.audioUploads),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_unit_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
