# Generated by Django 3.1.6 on 2021-03-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210328_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='longitude',
        ),
    ]
